[package]
edition = "2021"
name = "samuel"
version = "0.1.0"

[lib]
name = "samuel"
path = "src/lib/lib.rs"

[[bin]]
name = "samuel"
path = "src/bin/cli/bin.rs"

[dependencies]
clap = { version = "4.1.6", features = ["derive"] }
lazy_static = "1.3.0"
