[package]
name = "dothyphen-java"
version = "0.1.0"
edition = "2021"

[lib]
name = "dotjyphen"
crate-type = ["cdylib"]

[dependencies]
jni = "0.21.1"
dothyphen = { path = "../dothyphen", version = "0.2.1" }
