name: Manually publish members

on:
  workflow_dispatch:
    inputs:
      member:
        description: 'The name of the member to publish'
        required: true
        type: choice
        options:
        - dohy
        - dothyphen
        - dothyphen-fermyon
        - dothyphen-napi
        - dothyphen-wasm
      tag:
        description: 'The tag to publish'
        required: true
        type: string

jobs:
  crate:
    if: inputs.member == 'dohy' || inputs.member == 'dothyphen'
    name: Publish ${{ inputs.member }} to crates.io
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ inputs.tag }}
    - uses: dtolnay/rust-toolchain@stable
    - run: cargo publish -p ${{ inputs.member }} --token ${CARGO_REGISTRY_TOKEN}
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
  npm-wasm:
    if: inputs.member == 'dothyphen-wasm'
    name: Publish ${{ inputs.member }} to npmjs.com
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ inputs.tag }}
    - uses: dtolnay/rust-toolchain@stable
    - uses: jetli/wasm-pack-action@v0.4.0
      with:
        version: 'latest'
    - name: Build WebAssembly npm package
      run: make build-wasm-npm 
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        registry-url: 'https://registry.npmjs.org'
    - name: Publish package 
      run: cd dothyphen-wasm/output/wasm/npm && npm publish --access=public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTOMATION_TOKEN }}
  npm-napi:
    if: inputs.member == 'dothyphen-napi'
    uses: ./.github/workflows/napi.yml
    secrets:
      NPM_AUTOMATION_TOKEN: ${{ secrets.NPM_AUTOMATION_TOKEN }}
  fermyon:
    if: inputs.member == 'dothyphen-fermyon'
    name: Publish ${{ inputs.member }} to Fermyon Cloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.tag }}
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-wasi
      - uses: fermyon/actions/spin/setup@v1
      - name: Build and deploy to Fermyon
        uses: fermyon/actions/spin/deploy@v1
        with:
          manifest_file: dothyphen-fermyon/spin.toml
          fermyon_token: ${{ secrets.FERMYON_CLOUD_TOKEN }}