name: Manually publish packages

on:
  workflow_dispatch:
    inputs:
      package:
        description: 'The name of the package to publish'
        required: true
        type: choice
        options:
        - dohy
        - dothyphen
        - dothyphen-wasm
      tag:
        description: 'The tag to publish'
        required: true
        type: string

jobs:
  crate:
    if: inputs.package == 'dohy' || inputs.package == 'dothyphen'
    name: Publish ${{ inputs.package }} to crates.io
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ inputs.tag }}
    - uses: dtolnay/rust-toolchain@stable
    - run: cargo publish -p ${{ inputs.package }} --token ${CARGO_REGISTRY_TOKEN}
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
  npm:
    if: inputs.package == 'dothyphen-wasm'
    name: Publish ${{ inputs.package }} to npmjs.com
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ inputs.tag }}
    - uses: dtolnay/rust-toolchain@stable
    - uses: jetli/wasm-pack-action@v0.4.0
      with:
        version: 'latest'
    - name: Build WebAssembly npm package
      run: make build-wasm-npm 
    - uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        registry-url: 'https://registry.npmjs.org'
    - name: Publish package 
      run: cd dothyphen-wasm/output/wasm/npm && npm publish --access=public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}