name: Automatically run CI

on: [pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Check a local package and all of its dependencies for errors
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@stable
    - run: cargo check --workspace

  fmt:
    name: Run rustfmt in check mode
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@stable
    - run: cargo fmt --check

  clippy:
    name: Checks a package to catch common mistakes and improve the Rust code
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@stable
    - run: cargo clippy --no-deps

  unit:
    name: Execute all unit tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@stable
    - run: cargo test

  integration:
    name: Execute all integration tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@stable
      with:
        targets: 'wasm32-wasi'
    - uses: mwilliamson/setup-wasmtime-action@v2
      with:
        wasmtime-version: "13.0.0"
    - uses: jetli/wasm-pack-action@v0.4.0
      with:
        version: 'latest'
    - uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    - name: Run integration tests
      run: make test-integration